### ISSUE TITLE
什么情况下 int len = mSocket.EndReceive(ar); len==0？

### ISSUE THREAD

**Issue by jonny91** [LKaiGuo/KGNetSocket#1]
我有些时候会出现 int len = mSocket.EndReceive(ar); 
长度 == 0的情况 但是实际上客户端和服务器的链接并没有中断。
我现在的操作是如果==0 重新开始一个接收 Head 的异步方法

**Comment by LKaiGuo** [comment]
基本上不会存在0啊 你发消息需要new一个自定义类出来，而这个类序列化成byte[] 肯定会有长度   而且我还是往前面加上标长
 Socket关闭了 连接，并且所有可用数据均已收到，则 Receive 方法将立即完成并返回零字节。




------------------ 原始邮件 ------------------
发件人: "Always"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午2:51
收件人: "LKaiGuo/KGNetSocket"<KGNetSocket@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [LKaiGuo/KGNetSocket] 什么情况下 int len = mSocket.EndReceive(ar); len==0？ (#1)




我有些时候会出现 int len = mSocket.EndReceive(ar);
 长度 == 0的情况 但是实际上客户端和服务器的链接并没有中断。
 我现在的操作是如果==0 重新开始一个接收 Head 的异步方法

**Comment by jonny91** [comment]
对 我使用库里面的自己做一个服务器没这个问题。。我连接同事的JAVA服务器就会出这个问题。。
能肯定是 不是库的问题，我只是想不出有什么可能性。。所以问问你的想法。
